### ISSUE TITLE
Minecraft Launcher

### ISSUE THREAD

**Issue by BlackthornYugen** [Linaro/works-on-woa#77]
While Minecraft does run well on Arm the user experience isn't great because the launcher doesn't support arm. Is there a way to have this reflected on https://www.worksonwoa.com/games/minecraft/ or is this "out of scope" of the game's performance? 

![image](https://github.com/Linaro/works-on-woa/assets/3138467/6bfd46f7-2058-48c9-b61a-775480bd8cb8)

**Comment by Insane-Redditor** [comment]
Even with a launcher that **is** compatible with Arm, the game runs terribly. Hopefully the Linaro team listens and actually starts updating the game playability listings. Otherwise, people are just going to look at "Minecraft" and then think it runs wonderfully, since most people will just glance at it instead of looking down at the next one, which is Java Edition.

**Comment by wendyho** [comment]
Hello, please add any compatibility information for the game using the form on the contributing page, and we will update the game playability using user feedback. https://www.worksonwoa.com/contributing#games
